name: Coveralls

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x

    - name: Install dependencies and run tests
      run: |
        cd packages/common
        npm install
        npm test -- --coverage

    - name: Report Coveralls
      run: |
        npm install coveralls
        cat coverage/lcov.info | npx coveralls
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
